apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-quarkus-producer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kafka-quarkus-producer  
  template:
    metadata:
      labels:
        app: kafka-quarkus-producer
    spec:
      containers:
      - name: kafka-quarkus-producer
        image: quay.io/matzew/kafka-quarkus-producer
        imagePullPolicy: IfNotPresent
